# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rosters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffruleshift',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rosters.Shift'),
        ),
        migrations.AddField(
            model_name='staffruleshift',
            name='staff_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.StaffRule'),
        ),
        migrations.AddField(
            model_name='staffrule',
            name='day_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosters.DayGroup'),
        ),
        migrations.AddField(
            model_name='staffrule',
            name='shifts',
            field=models.ManyToManyField(through='rosters.StaffRuleShift', to='rosters.Shift'),
        ),
        migrations.AddField(
            model_name='staffrule',
            name='staff',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrulerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.Role'),
        ),
        migrations.AddField(
            model_name='shiftrulerole',
            name='shift_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.ShiftRule'),
        ),
        migrations.AddField(
            model_name='shiftrule',
            name='roles',
            field=models.ManyToManyField(through='rosters.ShiftRuleRole', to='rosters.Role'),
        ),
        migrations.AddField(
            model_name='shiftrule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.Shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='day_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosters.DayGroup'),
        ),
        migrations.AddField(
            model_name='preference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.Shift'),
        ),
        migrations.AddField(
            model_name='preference',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daygroupday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.Day'),
        ),
        migrations.AddField(
            model_name='daygroupday',
            name='day_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.DayGroup'),
        ),
    ]
