# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('plate_number', models.CharField(max_length=150)),
                ('vehicle_make_and_model', models.CharField(max_length=250)),
                ('vehicle_colour', models.CharField(max_length=100)),
                ('vehicle_purpose', models.CharField(max_length=150)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('production_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('odometer_start', models.CharField(max_length=150)),
                ('odometer_stop', models.CharField(max_length=150)),
                ('trip_distance', models.CharField(max_length=250)),
                ('fuel_station_used', models.CharField(max_length=250)),
                ('trip_information', models.CharField(max_length=250)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.Driver')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_reading', models.CharField(max_length=100)),
                ('refuel_date', models.DateField()),
                ('fuel_added', models.CharField(max_length=100)),
                ('fuel_cost', models.CharField(max_length=150)),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Vehicle')),
            ],
        ),
    ]
