# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awardees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='awards/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=250)),
                ('show_location', models.CharField(max_length=250)),
                ('showing_time', models.TimeField()),
                ('photo', models.ImageField(blank=True, upload_to='awards/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamCollaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_1', models.CharField(max_length=250)),
                ('image_1', models.ImageField(blank=True, upload_to='awards/')),
                ('full_name_2', models.CharField(max_length=250)),
                ('image_2', models.ImageField(blank=True, upload_to='awards/')),
                ('commendation', models.TextField()),
            ],
        ),
    ]
