# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('fault_description', models.CharField(max_length=150)),
                ('date_of_report', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('raised_by', models.CharField(max_length=255)),
                ('fixed_by', models.CharField(blank=True, max_length=250, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=250, null=True)),
                ('cause_of_breakdown', models.CharField(blank=True, max_length=255)),
                ('engineer_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Closed'), ('Being Reviewed', 'Being Reviewed')], default=False, max_length=250)),
            ],
        ),
    ]
