# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoeditor',
            name='video_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department'),
        ),
        migrations.AddField(
            model_name='preproductionschedule',
            name='director_of_photography_1',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='director_of_photography_1', to='user.Department'),
        ),
        migrations.AddField(
            model_name='preproductionschedule',
            name='director_of_photography_2',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='director_of_photography_2', to='user.Department'),
        ),
        migrations.AddField(
            model_name='preproductionschedule',
            name='director_of_photography_3',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='director_of_photography_3', to='user.Department'),
        ),
        migrations.AddField(
            model_name='preproductionschedule',
            name='director_of_photography_4',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='director_of_photography_4', to='user.Department'),
        ),
        migrations.AddField(
            model_name='preproductionschedule',
            name='producer_1',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='producer_1', to='user.Department'),
        ),
        migrations.AddField(
            model_name='preproductionschedule',
            name='producer_2',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='producer_2', to='user.Department'),
        ),
        migrations.AddField(
            model_name='graphicschedule',
            name='graphic_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.GraphicEditor'),
        ),
        migrations.AddField(
            model_name='graphiceditor',
            name='graphic_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department'),
        ),
        migrations.AddField(
            model_name='digitalschedule',
            name='digital_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.DigitalEditor'),
        ),
        migrations.AddField(
            model_name='digitaleditor',
            name='digital_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department'),
        ),
    ]
