# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('serial_no', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('New Item', 'New Item'), ('OI', 'Old Item')], default=False, max_length=250)),
                ('requested', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('close_request', models.BooleanField(default=False)),
                ('requested_by', models.CharField(default='user', max_length=250)),
                ('return_date', models.DateField()),
            ],
        ),
    ]
