# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('storeManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='assigned_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Department'),
        ),
    ]
