# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_comments', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('username', models.CharField(max_length=255)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
