# Generated by Django 3.0.7 on 2020-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('team_lead', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('venue_location', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('distribution_platform', models.CharField(max_length=250)),
                ('project_brief', models.CharField(max_length=250)),
            ],
        ),
    ]
